local vim = vim
local util = require 'utils'
local indent = util.setIndent;

indent('markdown', 4, true)
indent('apache', 4, true)
indent('aspvbs', 4, true)
indent('c', 4, true)
indent('cpp', 4, true)
indent('cs', 4, true)
indent('css', 2, true)
indent('json', 2, true)
indent('scss', 2, true)
indent('sass', 2, true)
indent('diff', 4, true)
indent('go', 2, true)
indent('eruby', 4, true)
indent('html', 2, true)
indent('java', 4, true)
indent('vue', 2, true)
indent('perl', 4, true)
indent('php', 2, true)
indent('python', 4, true)
indent('ruby', 2, true)
indent('haml', 2, true)
indent('sh', 4, true)
indent('sql', 4, true)
indent('vb', 4, true)
indent('vim', 2, true)
indent('wsh', 4, true)
indent('xhtml', 4, true)
indent('xml', 4, true)
indent('yaml', 2, true)
indent('zsh', 4, true)
indent('scala', 2, true)
indent('snippet', 4, true)
indent('glsl', 4, true)
indent('javascript', 2, true)
indent('javascript.jsx ', 2, true)
indent('javascriptreact', 2, true)
indent('typescript', 2, true)
indent('typescript.tsx', 2, true)
indent('typescriptreact', 2, true)
